CREATE DATABASE IF NOT EXISTS BD_CONSULTA_MEDICA;
USE BD_CONSULTA_MEDICA;

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA DATE  NOT NULL,
    HORARIO VARCHAR(5),
    FK_CPF_PACIENTE VARCHAR(14),
    FK_CRM_MEDICO VARCHAR(20),
    FOREIGN KEY (FK_CPF_PACIENTE) REFERENCES PACIENTE(CPF),
    FOREIGN KEY (FK_CRM_MEDICO) REFERENCES MEDICO(CRM)
);
