CREATE DATABASE IF NOT EXISTS BD_ESTQUE_MERCADO;
USE BD_ESTOQUE_MERCADO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VALIDADE VARCHAR(255),
    VALOR VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
	EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CNPJ_FORNECEDOR VARCHAR(20),
    FK_ID_PRODUTO INTEGER,
    FOREIGN KEY (FK_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ),
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO(ID)
);