CREATE DATABASE IF NOT EXISTS BD_GERENCIAMENTO_PROJETOS;
USE BD_GERENCIAMENTO_PROJETOS;

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRAZO VARCHAR(255) NOT NULL,
    PRECO DOUBLE NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(14) PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRAZO VARCHAR(255) NOT NULL,
    PRECO DOUBLE NOT NULL,
    FK_CPF_FUNCIONARIO VARCHAR(14),
    FK_ID_PROJETO INTEGER,
    FOREIGN KEY (FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO(CPF),
    FOREIGN KEY (FK_ID_PROJETO) REFERENCES PROJETO(ID)
);

CREATE TABLE IF NOT EXISTS FAZ(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CPF_FUNCIONARIO VARCHAR(14),
    FK_ID_TAREFA INTEGER,
    FOREIGN KEY (FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO(CPF),
    FOREIGN KEY (FK_ID_TAREFA) REFERENCES TAREFA(ID)
);