CREATE DATABASE IF NOT EXISTS BD_PASSAGENS_AEREAS;
USE BD_PASSAGENS_AEREAS;

CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LOCAL VARCHAR(255) NOT NULL,
    DATA VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(14) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
	NUMERO VARCHAR(50),
    CLASSE VARCHAR(255),
    FK_CPF_PASSAGEIRO VARCHAR(14),
    FK_ID_VOO INTEGER,
    FOREIGN KEY (FK_CPF_PASSAGEIRO) REFERENCES PASSAGEIRO(CPF),
    FOREIGN KEY (FK_ID_VOO) REFERENCES VOO(ID)
);
