CREATE DATABASE IF NOT EXISTS BD_STRIMING_VIDEOS;
USE BD_STRIMING_VIDEOS;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    IDADE INTEGER,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PUBLICO VARCHAR(255),
    DESCRICAO VARCHAR(255) NOT NULL,
    FK_ID_CATEGORIA INTEGER,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS VIZUALIZACAO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_VIDEO INTEGER,
    FOREIGN KEY (FK_ID_VIDEO) REFERENCES VIDEO(ID)
);